import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CounterProvider } from './context/CounterProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  team,
  analytics,
}: {
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <CounterProvider>{children}</CounterProvider>
        </div>
        <div>{team}</div>
        <div>{analytics}</div>
      </body>
    </html>
  );
}
